# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [69]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
op = np.array([3,5,9])
y= np.dot(X,op)
y=y.reshape(4,1)


In [70]:
##check y
print(op,op.shape)
print(y,y.shape)
#op=np.array([[3],[5],[9]])
#Y=X*op

[3 5 9] (3,)
[[ 9]
 [14]
 [12]
 [17]] (4, 1)


In [40]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
# define syn1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）



In [22]:
#add 
syn1 = 2*np.random.random((3,1)) - 1

In [8]:
##check 
print(syn0.shape)
print(syn0)

(3, 1)
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [72]:
for iter in range(10000):
    # forward propagation
    l0 = X
    #print("l0",l0.shape, "syn0",syn0.shape,"y",y.shape)
    l1 = nonlin(np.dot(l0,syn0))
    
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
    # how much did we miss?
    l1_error = y - l1
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    #print("shape:","l1_delta",l1_delta.shape, "l1_error",l1_error.shape)
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    print(syn0)
     # syn1 update weights
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l1)

[[ 5.63897132]
 [ 7.26383982]
 [11.47530881]]
[[ 5.63897173]
 [ 7.26383991]
 [11.47539237]]
[[ 5.63897213]
 [ 7.26384001]
 [11.47547593]]
[[ 5.63897254]
 [ 7.2638401 ]
 [11.47555948]]
[[ 5.63897295]
 [ 7.2638402 ]
 [11.47564303]]
[[ 5.63897335]
 [ 7.26384029]
 [11.47572657]]
[[ 5.63897376]
 [ 7.26384039]
 [11.4758101 ]]
[[ 5.63897417]
 [ 7.26384048]
 [11.47589362]]
[[ 5.63897457]
 [ 7.26384057]
 [11.47597714]]
[[ 5.63897498]
 [ 7.26384067]
 [11.47606065]]
[[ 5.63897539]
 [ 7.26384076]
 [11.47614415]]
[[ 5.63897579]
 [ 7.26384086]
 [11.47622765]]
[[ 5.6389762 ]
 [ 7.26384095]
 [11.47631114]]
[[ 5.6389766 ]
 [ 7.26384105]
 [11.47639462]]
[[ 5.63897701]
 [ 7.26384114]
 [11.4764781 ]]
[[ 5.63897742]
 [ 7.26384124]
 [11.47656157]]
[[ 5.63897782]
 [ 7.26384133]
 [11.47664503]]
[[ 5.63897823]
 [ 7.26384143]
 [11.47672848]]
[[ 5.63897864]
 [ 7.26384152]
 [11.47681193]]
[[ 5.63897904]
 [ 7.26384162]
 [11.47689537]]
[[ 5.63897945]
 [ 7.26384171]
 [11.47697881]]
[[ 5.63897985]
 [ 7.26384181]
 [11

In [63]:
np.dot(l0,syn0)

array([[-0.99977125],
       [-0.55912226],
       [-1.16572724],
       [-0.72507825]])

In [64]:
te= nonlin(np.dot(l0,syn0))

In [65]:
print(y.shape,te.shape)

(4,) (4, 1)


In [54]:
l1_error = y - l1

In [55]:
l1_error

array([[ 8.7310136 , 13.7310136 , 11.7310136 , 16.7310136 ],
       [ 8.63624942, 13.63624942, 11.63624942, 16.63624942],
       [ 8.76237183, 13.76237183, 11.76237183, 16.76237183],
       [ 8.6737243 , 13.6737243 , 11.6737243 , 16.6737243 ]])