# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [69]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
op = np.array([3,5,9])
y= np.dot(X,op)
y=y.reshape(4,1)


In [70]:
##check y
print(op,op.shape)
print(y,y.shape)
#op=np.array([[3],[5],[9]])
#Y=X*op

[3 5 9] (3,)
[[ 9]
 [14]
 [12]
 [17]] (4, 1)


In [40]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
# define syn1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）



In [22]:
#add 
syn1 = 2*np.random.random((3,1)) - 1

In [8]:
##check 
print(syn0.shape)
print(syn0)

(3, 1)
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [1]:
for iter in range(10000):
    # forward propagation
    l0 = X
    #print("l0",l0.shape, "syn0",syn0.shape,"y",y.shape)
    l1 = nonlin(np.dot(l0,syn0))
    
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
    # how much did we miss?
    l1_error = y - l1
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    #print("shape:","l1_delta",l1_delta.shape, "l1_error",l1_error.shape)
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    #print(syn0)
     # syn1 update weights
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l1)

NameError: name 'X' is not defined

In [63]:
np.dot(l0,syn0)

array([[-0.99977125],
       [-0.55912226],
       [-1.16572724],
       [-0.72507825]])

In [64]:
te= nonlin(np.dot(l0,syn0))

In [65]:
print(y.shape,te.shape)

(4,) (4, 1)


In [54]:
l1_error = y - l1

In [55]:
l1_error

array([[ 8.7310136 , 13.7310136 , 11.7310136 , 16.7310136 ],
       [ 8.63624942, 13.63624942, 11.63624942, 16.63624942],
       [ 8.76237183, 13.76237183, 11.76237183, 16.76237183],
       [ 8.6737243 , 13.6737243 , 11.6737243 , 16.6737243 ]])

In [3]:

import numpy as np
 
'''
定義數學函數:
y=f(x) = 1/(1+np.exp(-x));
dy/dx = df = x*(1-x) 

為了計算方便, 這邊把 y=f(x) 與 dy/dx 放在同一function 裡面;
利用 deriv (derivative)做變數, 來分別指定方程式

'''    
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
 
    return 1/(1+np.exp(-x))

# 參數定義
# X 輸入資料集，形式為矩陣，每 1 行代表 1 個訓練樣本。
# y 輸出資料集，形式為矩陣，每 1 行代表 1 個訓練樣本。

X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
 
y = np.array([[0],
            [1],
            [1],
            [0]])
 
np.random.seed(1)
 
# randomly initialize our weights with mean 0 
# syn0 第一層權值
# syn1 第二層權值

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

syn0_history = [syn0]
syn1_history = [syn1]
 
for j in range(60000):
 
    # Feed forward through layers 0, 1, and 2
    # l0 網路第 1 層，即網路輸入層。
    # l1 網路第 2 層，常稱作隱藏層。
    # l2 假定為網路最後一層，隨著訓練進行，其輸出應該逐漸接近正確結果
    
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
 
    # how much did we miss the target value?
    # l2_error 該值說明了神經網路預測時“丟失”的數目。
    # l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    # l1_error 該值為 l2_delta 經 syn1 加權後的結果，從而能夠計算得到中間層/隱層的誤差。
    # l1_delta 該值為經確信度加權後的神經網路 l1 層的誤差，除了確信誤差很小時，它近似等於 l1_error 。
    
    
    l2_error = y - l2
 
    if (j% 10000) == 0:
        print("L2_Error:" + str(np.mean(np.abs(l2_error))))
 
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
 
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    if (j% 10000) == 0:
        print("L1_Error:" + str(np.mean(np.abs(l2_error))))
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
 
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    syn1_history.append(syn1)
    syn0_history.append(syn0)

L2_Error:0.49641003190272537
L1_Error:0.49641003190272537
L2_Error:0.008584525653247152
L1_Error:0.008584525653247152
L2_Error:0.005789459862507806
L1_Error:0.005789459862507806
L2_Error:0.004629176776769986
L1_Error:0.004629176776769986
L2_Error:0.003958765280273646
L1_Error:0.003958765280273646
L2_Error:0.0035101225678616753
L1_Error:0.0035101225678616753
